version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.0

branches:
  only:
    - master
    - source

jobs:
  build:
    docker: 
      - image: cimg/ruby:2.7.4
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile" }}
            - rubygems-v1-fallback
      - run:
          command: gem install bundler -v '1.17.2'
      - run:
          command: bundle install  
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run: 
          command: bundle exec jekyll build --destination dist/
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: a8:c8:8f:f6:f8:e2:41:33:87:51:a2:62:f4:e7:17:d3
 
workflows:
  main:
    jobs:
      - build